### ISSUE TITLE
Chef client run fails while configuring interface with speed 10m on MX device

### ISSUE THREAD

**Issue by ganeshnalawade** [chef-partners/netdev#12]
Chef client run log
```
root@chef-client% /opt/sdk/chef/bin/ruby /opt/sdk/chef/bin/chef-client -c /config/chef/client.rb
[2015-06-11T11:15:36+05:30] INFO: Forking chef instance to converge...
Starting Chef Client, version 11.10.4
[2015-06-11T11:15:37+05:30] INFO: *** Chef 11.10.4 ***
[2015-06-11T11:15:37+05:30] INFO: Chef-client pid: 60669
[2015-06-11T11:15:43+05:30] INFO: Run List is [recipe[netdev::sample], recipe[netdev::vlan_create]]
[2015-06-11T11:15:43+05:30] INFO: Run List expands to [netdev::sample, netdev::vlan_create]
[2015-06-11T11:15:43+05:30] INFO: Starting Chef Run for chef-client
[2015-06-11T11:15:43+05:30] INFO: Running start handlers
[2015-06-11T11:15:43+05:30] INFO: Start handlers complete.
[2015-06-11T11:15:44+05:30] INFO: HTTP Request Returned 404 Object Not Found:
resolving cookbooks for run list: ["netdev::sample", "netdev::vlan_create"]
[2015-06-11T11:15:44+05:30] INFO: Loading cookbooks [netdev]
Synchronizing Cookbooks:
  - netdev
Compiling Cookbooks...
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:35: warning: already initialized constant KNOWN_RESOURCES
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:55: warning: already initialized constant L1ports
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:55: warning: already initialized constant L2ports
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:55: warning: already initialized constant IPports
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:55: warning: already initialized constant Vlans
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:55: warning: already initialized constant LAGports
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:65: warning: already initialized constant VALUES_TO_SYMBOLIZE
Converging 2 resources
Recipe: netdev::sample
  * netdev_interface[ge-1/0/0] action create[2015-06-11T11:15:48+05:30] INFO: Processing netdev_interface[ge-1/0/0] action create (netde
v::sample line 1)
[2015-06-11T11:15:51+05:30] INFO: Netconf session is sucess

================================================================================
Error executing action `create` on resource 'netdev_interface[ge-1/0/0]'
================================================================================

Chef::Exceptions::ValidationFailed
----------------------------------
Option speed must be equal to one of: auto, 100m, 1g, 10g, 40g, 56g, 100g!  You passed "10m".


Cookbook Trace:
---------------
/var/chef/cache/cookbooks/netdev/libraries/resource_interface.rb:102:in `speed'
/var/chef/cache/cookbooks/netdev/libraries/provider_interface_junos.rb:57:in `load_current_resource'


Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/netdev/recipes/sample.rb

  1: netdev_interface "ge-1/0/0" do
  2:   description "Created By Chef For Testing Purpose"
  3:   speed "1g"
  4:   duplex "full"
  5:   action :create
  6: end



Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/netdev/recipes/sample.rb:1:in `from_file'

netdev_interface("ge-1/0/0") do
  action [:create]
  retries 0
  retry_delay 2
  interface_name "ge-1/0/0"
  description "Created By Chef For Testing Purpose"
  enable true
  speed "1g"
  duplex "full"
  cookbook_name "netdev"
  recipe_name "sample"
end
[2015-06-11T11:15:52+05:30] INFO: Running queued delayed notifications before re-raising exception                            

Running handlers:
[2015-06-11T11:15:52+05:30] ERROR: Running exception handlers
[2015-06-11T11:15:52+05:30] INFO: Rolled back pending Junos candidate configuration changes
  - JunosCommitTransactionHandler
Running handlers complete

[2015-06-11T11:15:52+05:30] ERROR: Exception handlers complete
[2015-06-11T11:15:52+05:30] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 16.065309774 seconds
[2015-06-11T11:15:52+05:30] ERROR: netdev_interface[ge-1/0/0] (netdev::sample line 1) had an error: Chef::Exceptions::ValidationFailed:
Option speed must be equal to one of: auto, 100m, 1g, 10g, 40g, 56g, 100g!  You passed "10m".
[2015-06-11T11:15:52+05:30] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Acceptable value of speed on mx80
```
user@mx-chef# set interfaces ge-1/1/1 speed ?
Possible completions:
  100m
  10m
  1g
  auto                 Enable auto negotiation of interface speed
```

**Comment by ganeshnalawade** [comment]
This change fixes the issue https://github.com/opscode-cookbooks/netdev/commit/f3d1a0cb8cc0c7b09c986578a2eba633012d880d
